apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-guestbook-a-dev
  namespace: argocd
spec:
  project: helm-guestbook-a
  source:
    repoURL: https://github.com/jerrycan321/helm-kustomize-poc.git # Repository containing the Kustomization.yaml file
    targetRevision: HEAD
    path: eu-west-2/prod/applications/customer1 # Path to folder for kustomization.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
